### ISSUE TITLE
picker组件

### ISSUE THREAD

**Issue by maczyt** [justjavac/awesome-wechat-weapp#36]
> 在默认选择器中，点击切换，事件监听正常，但是出现一个错误

``` js
WAService.js:2 SyntaxError: Unexpected token u in JSON at position 0
    at t.deepCopy (http://2102000433.appservice.open.weixin.qq.com/WAService.js:2:22010)
    at e.value (http://2102000433.appservice.open.weixin.qq.com/WAService.js:2:17625)
    at e.bindPickerChange (http://2102000433.appservice.open.weixin.qq.com/pages/test/test.js:41:10)
    at m (http://2102000433.appservice.open.weixin.qq.com/WAService.js:2:10656)
    at .<anonymous> (http://2102000433.appservice.open.weixin.qq.com/WAService.js:2:11957)
    at http://2102000433.appservice.open.weixin.qq.com/WAService.js:2:21703
    at http://2102000433.appservice.open.weixin.qq.com/WAService.js:1:15767
    at Object.e.(anonymous function) [as PAGE_EVENT] (http://2102000433.appservice.open.weixin.qq.com/WAService.js:1:18968)
    at a (http://2102000433.appservice.open.weixin.qq.com/asdebug.js:1:1386)
    at http://2102000433.appservice.open.weixin.qq.com/asdebug.js:1:6717t.errorReport @ WAService.js:2value @ WAService.js:2bindPickerChange @ test.js:41m @ WAService.js:2(anonymous function) @ WAService.js:2(anonymous function) @ WAService.js:2(anonymous function) @ WAService.js:1e.(anonymous function) @ WAService.js:1a @ asdebug.js:1(anonymous function) @ asdebug.js:1
```

**求解答**

**Comment by justjavac** [comment]
issues 不是答疑的地方，而且这个项目也不是小程序答疑repo
